//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table4
    {
        public int Id { get; set; }
        public string Bus_No { get; set; }
        public string Engine_Number { get; set; }
        public string Departure_City { get; set; }
        public string Destination_City { get; set; }
        public string Departure_Timing { get; set; }
        public int Driver_ID { get; set; }
        public int Available_Seats { get; set; }
        public string Bus_Class { get; set; }
        public int Total_Seats { get; set; }
        public int Price { get; set; }
    }
}
