//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table3
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Cnic { get; set; }
        public int Licence_ { get; set; }
        public string Address { get; set; }
        public int contact { get; set; }
    }
}
