//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SemesterProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table2
    {
        public int Id { get; set; }
        public string Departure_City { get; set; }
        public string Destination_City { get; set; }
        public string Bus_Class { get; set; }
        public string Timing { get; set; }
        public decimal Account_Number { get; set; }
    }
}
